repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.8.4
  hooks:
    # Run the linter.
    - id: ruff
      name: lint with ruff
    - id: ruff
      name: sort imports with ruff
      args: [--select, I, --fix]
    # Run the formatter.
    - id: ruff-format
      name: format with ruff

- repo: https://github.com/DanielNoord/pydocstringformatter
  rev: v0.7.3
  hooks:
    - id: pydocstringformatter

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json

# TODO:
# - repo: https://github.com/pre-commit/mirrors-pyright
#   rev: v1.1.370
#   hooks:
#     - id: pyright
#       name: type-check with pyright
